ALTER TABLE PREPAREDQUERYRESULTHEADERS ADD ISDEFAULTORDER NUMBER(1,0) NULL;

CREATE OR REPLACE PROCEDURE GETPREPAREDQUERYRESULTHEADERS
(
   pPQId  IN NUMBER,
   v_cursor OUT SYS_REFCURSOR
)
AS

BEGIN
       OPEN  v_cursor FOR
SELECT 
   ID, PQID, ENTITYID, ATTRIBUTEID, HEADERALIAS, HEADERORDER, ENTITYALIAS, ISDEFAULTORDER
FROM
    PREPAREDQUERYRESULTHEADERS 
WHERE
    PQID  = pPQId
ORDER BY HEADERORDER;
END;
-----------------------------------------------------
CREATE OR REPLACE PROCEDURE CREATEPREPAREDQUERYRESULTHEADER
(
    pPQId IN NUMBER,
    pEntityId IN NUMBER,
    pAttributeId IN NUMBER,
    pHeaderAlias IN VARCHAR2,
    pHeaderOrder IN NUMBER,
    pEntityAlias IN VARCHAR2,
    pIsDefaultOrder IN NUMBER
)
AS

BEGIN

INSERT INTO 
    PREPAREDQUERYRESULTHEADERS
(PQID, ENTITYID, ATTRIBUTEID, HEADERALIAS, HEADERORDER, ENTITYALIAS, ISDEFAULTORDER)
VALUES(pPQId, pEntityId, pAttributeId, pHeaderAlias, pHeaderOrder, pEntityAlias, pIsDefaultOrder);

END;

INSERT INTO TNRK_MIGRATIONS (NAME,RECORD_DATE) VALUES('20230902_2226.sql', CURRENT_TIMESTAMP);
