ALTER TABLE SYSSCENARIO_FILTER_HISTORY MODIFY VALUE VARCHAR2(4000);
ALTER TABLE SYSSCENARIO_FILTER_HISTORY MODIFY OLD_VALUE VARCHAR2(4000);

INSERT INTO TNRK_MIGRATIONS (NAME,RECORD_DATE) VALUES('20230821_0852.sql', CURRENT_TIMESTAMP);